import { PLAYER_ATTACKS, MONSTER_ATTACKS, DEFEATS } from './combat_logs_data';

export const ROOM_DESCRIPTIONS = [
  "The room smells of ozone and disappointment. The walls are lined with filing cabinets that seem to contain nothing but redacted personnel files from the 1970s.",
  "A large, circular chamber that feels like it was designed by someone who had only a theoretical understanding of Euclidean geometry. The corners don't quite meet.",
  "This area is dominated by a low hum that you feel in your teeth rather than hear. It's the kind of sound a refrigerator makes right before it decides to stop working forever.",
  "The floor here is sticky, but not in a way that suggests spilled soda. It's more like the floor itself is sweating from anxiety.",
  "You enter a space that feels aggressively neutral, like a dentist's waiting room where the magazines are all from a timeline where the Nazis won.",
  "The lighting in this room flickers with a rhythm that almost sounds like Morse code, spelling out a message you are grateful you cannot decode.",
  "A cramped, claustrophobic hallway that opens into a room filled with empty cages. The bars are bent outward.",
  "This room contains a single chair in the center, facing a wall. The wall has scratch marks that look suspiciously like a calendar.",
  "The air here is thick with dust that tastes like copper. Every step you take kicks up a cloud of what you hope is just dirt.",
  "A vast, empty hall that echoes with the sound of your own breathing, which sounds increasingly ragged and pathetic.",
  "The ceiling here is uncomfortably low, forcing you to hunch over like a subservient creature before an unseen master.",
  "This room is filled with pipes that gurgle with a wet, organic sound. You try not to think about what is flowing through them.",
  "A library of sorts, but the books are all blank. Or maybe they aren't, and your mind just refuses to process the text.",
  "The walls are covered in mold that forms patterns resembling the faces of people you went to high school with.",
  "You step into a room that feels colder than the rest of the basement. Your breath fogs in the air, forming shapes that look like screaming mouths.",
  "This area smells of formaldehyde and cheap cologne. It reminds you of a funeral for a distant relative you didn't really like.",
  "The floor is tiled in a checkerboard pattern, but the black squares seem to be holes into an infinite void.",
  "A room filled with broken scientific equipment. Glass shards crunch under your feet like the shattered dreams of a tenured professor.",
  "The shadows in this room seem to move independently of the light source. They pool in the corners like spilled ink.",
  "You enter a room that is perfectly clean, which is somehow more disturbing than the filth elsewhere. It feels like a stage set for a tragedy.",
  "The walls are plastered with layers of peeling wallpaper, each layer revealing a different era of bad taste. Underneath the final layer, you glimpse a writing that looks like it was scratched by fingernails, detailing a recipe for a soup made of memories.",
  "A small, windowless office that smells of stale coffee and despair. A single computer monitor hums on a desk, displaying a screensaver of pipes that twist into impossible knots. You feel a sudden urge to update a spreadsheet.",
  "This room is filled with mirrors, but none of them reflect you. Instead, they show a version of you that made better life choices, looking happy and fulfilled. It is the most terrifying thing you have seen so far.",
  "The air is heavy with the scent of old books and decaying flowers. Shelves line the walls, filled with jars containing what look like preserved emotions. One jar labeled 'Hope' is cracked and empty.",
  "You step into a room where gravity feels slightly askew. You have to lean at a 45-degree angle just to stand upright. The furniture is bolted to the ceiling, which is now the floor, or maybe the wall. It's confusing.",
  "A vast, subterranean garden where the plants are made of wire and glass. They rustle in a non-existent breeze, creating a sound like a thousand wind chimes being smashed with a hammer.",
  "The floor is covered in a thick, plush carpet that feels disturbingly like fur. It pulses gently under your feet, as if the room itself is a giant, sleeping beast. You try to tread lightly.",
  "This chamber is dominated by a massive clock face on the floor. The hands are spinning backwards at a dizzying speed. You feel yourself getting younger, then older, then younger again in rapid succession.",
  "The room is filled with statues of people cowering in fear. As you move, you swear their heads turn to follow you. One of them looks suspiciously like your high school math teacher.",
  "A kitchen area that looks like it was abandoned in the middle of preparing a meal. A pot on the stove is still boiling, but the liquid inside is black and viscous. The refrigerator is humming a tune you recognize but can't place.",
  "You enter a room that is entirely white. White floor, white walls, white ceiling. The brightness is blinding. After a moment, you realize there are no shadows here, not even your own.",
  "This room is filled with filing cabinets that stretch up into the darkness above. You open one at random and find a file containing a detailed transcript of every conversation you've ever had. The last entry is from five minutes ago.",
  "The walls are covered in ticking clocks of all shapes and sizes. The ticking is not synchronized, creating a chaotic rhythm that threatens to induce a migraine. Every so often, they all stop at once for a full second of deafening silence.",
  "A long, narrow hallway lined with portraits of people whose eyes have been scratched out. The frames are made of bone. At the end of the hall, a mirror reflects the back of your head, no matter which way you turn.",
  "This room smells of ozone and burnt hair. In the center sits a chair with leather straps and a metal helmet. A sign on the wall reads 'Thinking Cap - Do Not Overuse'.",
  "The floor is made of glass, revealing a deep, dark abyss below. Something massive and bioluminescent swims in the depths, its eye larger than the room you are standing in.",
  "You enter a room that appears to be a child's nursery, but everything is wrong. The crib is made of barbed wire, the mobile hangs with dried bones, and the teddy bear has real teeth.",
  "The air is thick with a green mist that smells of mint and rot. Shapes move in the fog, always just out of your peripheral vision. You hear a whispering that sounds like your own voice.",
  "This room is a replica of your childhood bedroom, but everything is slightly too large. You feel small and vulnerable, like a toddler in a world of giants.",
  "A room filled with mannequins dressed in clothes from different decades. They are all posed as if they are running away from something. You look behind you, but there is nothing there.",
  "The walls are made of flesh that quivers when you touch it. Veins pulse with a blue fluid. A mouth in the wall opens and asks for a glass of water.",
  "You step into a room that is upside down. The chandelier is on the floor, and the rug is on the ceiling. You feel a wave of nausea as your brain tries to reconcile the visual data.",
  "This area is a library where the books fly off the shelves and attack you like angry birds. You have to dodge a copy of 'War and Peace' to get to the other side.",
  "The room is filled with a thick, cloying smoke that smells of incense and burnt sugar. Through the haze, you see figures dancing in a circle, but they have too many limbs.",
  "A laboratory filled with bubbling beakers and Tesla coils. A brain in a jar follows your movements with its eye stalk. It taps on the glass in Morse code: 'Let me out'.",
  "You enter a room that is completely dark. You can't see your hand in front of your face. You hear breathing that is definitely not yours, right next to your ear.",
  "This room is a giant chessboard. The pieces are life-sized and made of stone. The Black Queen turns to look at you and winks.",
  "The floor is covered in water that is ankle-deep. It is crystal clear, and you can see fish swimming around your boots. The fish have human faces.",
  "A room filled with mirrors that distort your reflection into monstrous shapes. In one mirror, you are a skeleton. In another, you are a blob of slime. You wonder which one is the truth.",
  "The walls are lined with jars of formaldehyde containing preserved specimens of creatures that defy classification. One jar is labeled 'The Player's Dignity' and is empty.",
  "You enter a room that smells of old paper and ink. Scrolls are piled high on every surface. You pick one up and it crumbles to dust in your hands.",
  "This room is a greenhouse filled with carnivorous plants. They snap their jaws at you as you pass. One of them whispers, 'Feed me, Seymour'.",
  "The floor is made of loose tiles that shift under your feet. Below the tiles, you see a mechanism of gears and cogs that seems to power the entire dungeon.",
  "A room filled with musical instruments that play themselves. The melody is haunting and discordant. A violin screeches as you walk by.",
  "You step into a room that is freezing cold. Icicles hang from the ceiling, and your breath comes out in white puffs. Frozen in a block of ice in the center is a figure that looks like you.",
  "This area is a torture chamber with devices that look like they were designed by M.C. Escher. You can't figure out how they would work, and you don't want to find out.",
  "The walls are covered in graffiti written in a language you don't understand. The letters seem to writhe and change shape when you look at them directly.",
  "A room filled with statues of weeping angels. You remember the rule: don't blink. You back out of the room slowly, eyes wide open.",
  "The floor is sticky with a substance that looks like honey but smells like blood. Bees the size of cats buzz around a hive in the corner.",
  "You enter a room that is a perfect replica of the Oval Office, but the desk is covered in tentacles. A phone rings, but when you answer it, there is only screaming."
];

export const COMBAT_LOGS = {
  playerAttack: PLAYER_ATTACKS,
  monsterAttack: MONSTER_ATTACKS,
  defeat: DEFEATS
};
