export const ALTAR_DESCRIPTIONS = [
  "A stone altar covered in dried, dark blood. It suggests a level of ritualistic commitment that is both impressive and deeply, deeply problematic.",
  "The altar is made of a bone-white stone that feels warm to the touch. The bloodstains on it form a pattern that looks disturbingly like a smiley face.",
  "A rough-hewn slab of granite, slick with fresh ichor. It smells of copper and ozone, a combination that shouldn't exist in nature.",
  "This altar is covered in candles that burn with a cold, blue flame. The wax has dripped down the sides, forming shapes that look like grasping hands.",
  "A small, portable altar made of driftwood. It looks like something a castaway would build to worship a coconut god, but with more blood.",
  "The altar is carved from a single giant tooth. You don't want to know what creature it came from, but you can guess it didn't floss.",
  "A obsidian block that seems to absorb the light around it. The blood on top is bubbling slightly, as if it's boiling.",
  "This altar is covered in feathers and small bones. It looks like a bird's nest, if the bird was a psychopath.",
  "A metal table with gutters for draining fluids. It's efficient, industrial, and completely soulless.",
  "The altar is made of ice that never melts. The blood on it is frozen in perfect, red droplets.",
  "A wooden stump that has been used as a chopping block. The rings of the wood are stained deep red.",
  "This altar is actually a repurposed office desk. The 'In' tray is full of organs.",
  "A pile of skulls arranged in a pyramid. The top skull has a flat surface carved into it, which is currently occupied by a beating heart.",
  "The altar is made of living flesh that quivers when you approach. It's gross. Really, really gross.",
  "A glass table that is perfectly clear, except for the blood smeared on top. You can see the floor through it, which is also covered in blood.",
  "This altar is covered in gold leaf, which is peeling away to reveal rotting wood underneath. A metaphor for something, probably.",
  "A simple stone block with a single, perfect rose placed in the center of a pool of blood.",
  "The altar is surrounded by a circle of salt that has been broken. Whatever was inside has escaped.",
  "A holographic projection of an altar. The blood is digital, but the horror feels real enough.",
  "This altar is made of old computer parts. The blood is leaking into the keyboard.",
  "A stack of books arranged to form a flat surface. The top book is 'Cooking with Humans'.",
  "The altar is floating a few inches off the ground. It hums with a low, menacing vibration.",
  "A mirror laid flat on the ground. When you look into it, you see the altar, but not yourself.",
  "This altar is covered in cobwebs. It hasn't been used in a while, which is somehow more ominous.",
  "A block of salt that has been carved into an altar. The blood is dissolving it slowly.",
  "The altar is made of tightly packed dirt. Worms crawl in and out of the blood-soaked earth.",
  "A marble pedestal with a bust of a tentacled monster. The blood is poured over the head like a libation.",
  "This altar is covered in photographs of people you don't know. Their eyes have been scratched out.",
  "A rusty metal box with a flat top. You can hear scratching coming from inside.",
  "The altar is made of Legos. It's a masterpiece of childhood creativity and adult trauma.",
  "A tree stump that is growing out of the stone floor. The sap looks suspiciously like blood.",
  "This altar is covered in glitter. It's festive, in a horrific sort of way.",
  "A block of cheese. Yes, cheese. It's moldy and covered in blood. The smell is indescribable.",
  "The altar is made of soap. It's slippery with blood.",
  "A giant mushroom with a flat cap. The spores it releases make you feel dizzy.",
  "This altar is actually a mimic. It's sleeping, but the blood on its 'surface' is real.",
  "A pile of dirty laundry that has stiffened into a solid mass. The bloodstains are the least of its problems.",
  "The altar is made of crystal that sings when the wind blows. The song is a scream.",
  "A cardboard box with 'ALTAR' written on the side in crayon.",
  "This altar is covered in clocks, all stopped at 3:33 AM.",
  "A block of ice with a fish frozen inside. The fish is looking at you.",
  "The altar is made of compacted trash. It's a monument to waste and death.",
  "A giant turtle shell. The turtle is long gone, but the blood remains.",
  "This altar is covered in tarot cards. The Death card is face up.",
  "A pool table. The pockets are full of blood.",
  "The altar is made of bread. It's stale and hard as a rock.",
  "A suitcase. It's open, and the inside is lined with velvet and blood.",
  "This altar is a giant hand, palm up. It's made of stone, but the lifelines are etched in red.",
  "A toilet. Just a toilet. It's broken and covered in blood. Very undignified.",
  "The altar is invisible. You only know it's there because you bumped into it and got blood on your pants."
];

export const CARVING_DESCRIPTIONS = [
  "The walls are covered in geometries that seem to actively loathe the concept of a right angle.",
  "Strange symbols that look like they were carved by a claw, or perhaps a very angry fork.",
  "A mural depicting the end of the world. It's very detailed, right down to the tiny, screaming figures.",
  "Carvings of eyes that seem to blink when you're not looking directly at them.",
  "A series of mathematical equations that solve for 'doom'.",
  "The stone is etched with a map of the stars, but the constellations are all wrong.",
  "A bas-relief of a tentacled monster eating a picnic lunch. The sandwich is a person.",
  "Carvings that look like QR codes. You are tempted to scan one, but decide against it.",
  "A depiction of a city under the sea. The fish look bored.",
  "The walls are covered in text written in a language that hurts your eyes to read.",
  "A carving of a door that isn't there. You try to open it, but it's just rock.",
  "Symbols that glow with a faint, green light. They pulse in time with your heartbeat.",
  "A carving of a giant worm devouring the sun. It's a bit melodramatic.",
  "The stone is scratched with thousands of tally marks. Someone was counting something, and they reached a very high number.",
  "A depiction of a ritual involving goats and kazoos. It's weirdly specific.",
  "Carvings of faces that are screaming silently. You can almost hear them.",
  "A diagram of a human body, but with the organs rearranged.",
  "The walls are covered in handprints carved into the stone. They are all different sizes, but none of them are human.",
  "A carving of a spiral that goes on forever. If you look at it too long, you get dizzy.",
  "Symbols that look like musical notes, but the staff has five lines instead of four.",
  "A depiction of a battle between monsters and robots. The robots are losing.",
  "The stone is etched with a warning: 'Don't look behind you'. You look behind you. Nothing is there.",
  "A carving of a cat. It's the only normal thing you've seen all day.",
  "The walls are covered in what looks like a menu for a restaurant that serves souls.",
  "A depiction of a giant eye. It's crying blood.",
  "Carvings of people dancing. They look happy, which is suspicious.",
  "A map of the dungeon. It says 'You are here', but the arrow points to a pit of spikes.",
  "The stone is etched with a love letter to a shoggoth. It's surprisingly tender.",
  "A carving of a clock that has no hands.",
  "Symbols that look like emojis, but evil. The poop emoji has fangs.",
  "A depiction of a king sitting on a throne of bones. He looks lonely.",
  "The walls are covered in scratches that form the word 'RUN' over and over again.",
  "A carving of a giant spider. It's very realistic.",
  "The stone is etched with a recipe for disaster.",
  "A depiction of a boat sailing on a sea of fire.",
  "Carvings of birds falling from the sky.",
  "A diagram of a machine that turns dreams into nightmares.",
  "The walls are covered in fingerprints carved into the stone.",
  "A carving of a snake eating its own tail. Classic.",
  "Symbols that look like constellations, but they form the shape of a middle finger.",
  "A depiction of a giant mouth. It's open wide.",
  "The stone is etched with a list of names. Yours is at the bottom.",
  "A carving of a key. It doesn't fit any lock you've found.",
  "The walls are covered in what looks like a child's drawing of a monster.",
  "A depiction of a sun that is black.",
  "Carvings of fish with legs.",
  "A diagram of the solar system, but Earth is missing.",
  "The stone is etched with a poem about death. It doesn't rhyme.",
  "A carving of a giant hand crushing a city.",
  "The walls are blank, but you can feel the carvings with your fingers."
];
