export const META_COMMENTARY = [
  "The player pauses, perhaps considering the futility of their actions, or maybe just checking a text message.",
  "You feel a sudden, overwhelming sense that your entire existence is being rendered by a JavaScript framework.",
  "A moment of silence stretches out, heavy with the weight of unmade choices and the faint hum of a cooling fan.",
  "You wonder if the monsters are truly evil, or just victims of procedural generation algorithms with poor impulse control.",
  "The dungeon walls seem to vibrate with the anxiety of being observed by a user who might close the tab at any moment.",
  "You are struck by the realization that your inventory management skills are a direct reflection of your inability to organize your own life.",
  "For a second, the interface flickers, revealing the void of code beneath the surface of the game's reality.",
  "You consider the possibility that you are not the protagonist, but merely a cursor moving through a pre-determined set of coordinates.",
  "The darkness ahead looks less like an absence of light and more like a failure of the rendering engine to load the next chunk.",
  "You feel a strange kinship with the NPCs, trapped in their loops of dialogue, forever waiting for an interaction that may never come.",
  "The act of moving forward feels less like progress and more like a compulsive need to see what happens next, regardless of the quality of the content.",
  "You are seized by the fear that all your achievements here will be wiped away by a browser refresh, a digital memento mori.",
  "The combat log scrolls by, a textual record of violence that feels both immediate and incredibly distant, like reading about a war in a history book.",
  "You pause to admire the pixel art, wondering if the artist intended for the bloodstains to look so much like spilled jam.",
  "The background music loops, a repetitive drone that mirrors the circular nature of your own thoughts.",
  "You feel a phantom itch in a limb you don't possess, a glitch in the sensory feedback loop of the simulation.",
  "The game's difficulty curve feels less like a challenge and more like a personal insult from the developer.",
  "You wonder if the random number generator is truly random, or if it holds a grudge against you specifically.",
  "The silence of the dungeon is broken only by the sound of your own keystrokes, a rhythmic reminder of the physical world you are ignoring.",
  "You stare at the screen, and for a moment, the screen stares back, judging your posture and your hydration levels.",
  "The narrative structure of this experience is beginning to feel suspiciously like a metaphor for late-stage capitalism.",
  "You find yourself empathizing with the loot drops, objects whose only value is determined by their utility to a transient hero.",
  "The level design feels like a maze constructed by a sadist with a degree in behavioral psychology.",
  "You are overcome with a sense of déjà vu, as if you have died in this exact spot a thousand times before in a thousand different timelines.",
  "The text on the screen blurs, the words losing their meaning and becoming mere shapes, signifiers without signifieds.",
  "You wonder if the 'Game Over' screen is a threat or a promise of release from the cycle of struggle.",
  "The act of healing yourself feels like a temporary stay of execution, a postponement of the inevitable entropy.",
  "You are trapped in a Skinner box of your own making, pressing buttons for dopamine hits that are diminishing with every click.",
  "The monsters' AI seems to be fluctuating between 'mindless aggression' and 'existential dread,' much like your own internal monologue.",
  "You realize that the true horror of the dungeon is not the monsters, but the infinite regress of levels with no ultimate purpose.",
  "The game's mechanics feel like a set of arbitrary rules imposed on a chaotic universe to create the illusion of order.",
  "You pause to consider the ethical implications of looting the dead, then remember that they are just sprites and you need the gold.",
  "The flickering torchlight casts shadows that look suspiciously like the silhouettes of your own insecurities.",
  "You feel a sudden urge to break the fourth wall, but realize there is no audience, only the cold, unfeeling logic of the code.",
  "The dungeon's atmosphere is thick with a specific kind of digital melancholy, the sadness of a world that only exists when someone is looking at it.",
  "You wonder if the developer is watching you play, a silent god judging your efficiency and your moral choices.",
  "The repetitive nature of the combat feels like a commentary on the grind of daily life, or maybe just lazy game design.",
  "You are struck by the absurdity of your quest, a hero's journey reduced to a series of fetch quests and stat checks.",
  "The game's lore feels like a fragmented narrative that you are trying to piece together, much like your own memories of last Tuesday.",
  "You feel a strange disconnection from your avatar, as if you are puppeteering a stranger through a nightmare.",
  "The darkness of the dungeon is not just an absence of light, but a presence of something else, something vast and indifferent.",
  "You wonder if the game has an ending, or if it just goes on forever, generating new levels until the heat death of the universe.",
  "The items in your inventory feel heavy, burdened with the weight of their own descriptions and the expectations placed upon them.",
  "You are fighting not just for survival, but for meaning in a world that seems determined to deny it to you.",
  "The sound effects are starting to grate on your nerves, a repetitive auditory assault that mirrors the relentless pace of modern life.",
  "You feel a sudden, intense desire to turn off the game and go outside, but the allure of the next level keeps you tethered.",
  "The game's interface is a barrier between you and the experience, a constant reminder that you are an observer, not a participant.",
  "You wonder if the monsters have families, dreams, aspirations, or if they are just code waiting to be executed.",
  "The act of saving the game feels like a desperate attempt to preserve a moment in time against the relentless march of entropy.",
  "You are playing a game within a game, a simulation within a simulation, and you can't remember where the real world ends and the digital one begins.",
  "The dungeon is a mirror, reflecting back not your face, but your fears, your desires, and your infinite capacity for boredom.",
  "You feel a sudden pang of sympathy for the CPU cycles being burned to render this specific instance of despair.",
  "The dungeon layout reminds you of a particularly confusing IKEA instruction manual for a piece of furniture called 'EXISTENTIAL DREAD'.",
  "You pause to wonder if your avatar has a backstory, or if they simply popped into existence the moment you clicked 'Start Game'.",
  "The silence is punctuated by the sound of your own breathing, which sounds suspiciously like a looped audio file.",
  "You are struck by the thought that every monster you kill is just a variable being set to null.",
  "The loot you find feels less like a reward and more like a bribe to keep you playing.",
  "You wonder if the game's physics engine can simulate the weight of your regrets.",
  "The flickering lights seem to be communicating in binary, spelling out 'HELP ME' over and over again.",
  "You feel a strange sense of voyeurism, as if you are watching someone else's nightmare.",
  "The game's color palette seems to be composed entirely of shades of 'bruise' and 'decay'.",
  "You are seized by the fear that the game is playing you, rather than the other way around.",
  "The repetitive motion of clicking the mouse feels like a prayer to a god who isn't listening.",
  "You wonder if the NPCs talk about you when you're not around, critiquing your playstyle.",
  "The dungeon feels less like a physical space and more like a manifestation of the developer's unresolved childhood trauma.",
  "You are overcome with the urge to apologize to the monsters for interrupting their day.",
  "The game's lore is so dense it threatens to collapse into a black hole of exposition.",
  "You feel a phantom vibration in your pocket, a ghost notification from a world you have left behind.",
  "The shadows seem to be lengthening, reaching out to drag you into the code.",
  "You wonder if your high score will be remembered by anyone, or if it will simply vanish into the digital ether.",
  "The act of leveling up feels like a hollow victory, a numerical increase in a world without meaning.",
  "You are trapped in a loop of violence and looting, a hamster on a wheel made of pixels.",
  "The game's soundtrack sounds like it was composed by a depressed robot.",
  "You feel a sudden, intense connection to the wall texture, as if it holds the secrets of the universe.",
  "The monsters' death animations are starting to look a bit too realistic for comfort.",
  "You wonder if the game is a test, and if so, what exactly is being tested.",
  "The interface feels clunky, a relic of a bygone era of user experience design.",
  "You are struck by the realization that you are spending your finite time on this earth fighting imaginary monsters.",
  "The dungeon seems to be rearranging itself when you're not looking, a gaslighting architecture.",
  "You feel a sudden urge to write a strongly worded review, but realize there is no one to read it.",
  "The game's economy is broken, much like the economy of the real world.",
  "You wonder if the developer included any easter eggs, or if the whole game is just one long, unfunny joke.",
  "The silence is deafening, a roar of white noise that drowns out your thoughts.",
  "You feel a strange compulsion to check your stats, as if they define your worth as a human being.",
  "The monsters seem to be getting smarter, or maybe you are just getting dumber.",
  "You are trapped in a digital purgatory, waiting for a server reset that will never come.",
  "The game's collision detection is a bit wonky, much like your own sense of personal boundaries.",
  "You wonder if the game has a soul, or if it is just a cold, unfeeling machine.",
  "The act of drinking a potion feels like a desperate attempt to self-medicate.",
  "You are struck by the beauty of the lighting engine, a fleeting moment of grace in a world of ugliness.",
  "The dungeon smells of ozone and stale pizza, a sensory hallucination brought on by sleep deprivation.",
  "You feel a sudden, intense loneliness, a realization that you are the only real thing in this world.",
  "The game's framerate drops, a stutter in the fabric of reality.",
  "You wonder if the monsters are afraid of you, or if they just see you as another bug to be squashed.",
  "The act of pausing the game feels like holding your breath, a temporary suspension of disbelief.",
  "You are trapped in a narrative cul-de-sac, spinning your wheels in a plot that isn't going anywhere.",
  "The game's font choice is questionable, a typographic crime against humanity.",
  "You feel a sudden urge to rage-quit, but the sunk cost fallacy keeps you playing.",
  "The dungeon is a metaphor for your own mind, a dark and twisting labyrinth filled with monsters.",
  "You wonder if you will ever escape, or if you are doomed to wander these halls forever.",
  "The game crashes, and for a moment, you are free."
];
